### ISSUE TITLE
Feature request: Update button

### ISSUE THREAD

**Issue by illuzor** [SlavaRa/fd-antpanel-plugin#10]
"Update" button on panel.
If tasks changed/removed/created/renamed, this changes not displaing on the panel.
Need to restart FlashDevelop to see changes.
Would be great to make ability to update view by button.

**Comment by SlavaRa** [comment]
Hi, ![](http://service.crazypanda.ru/v/clip2net/c/6/Elp77AzAMR.png)

**Comment by illuzor** [comment]
Ok.
![upd](https://cloud.githubusercontent.com/assets/1530314/6840588/4c24503a-d38c-11e4-9566-34e90a3bd34c.png)
